apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Service.yaml

images:
- name: app-reports
  newName: manscalh/app-reports
  newTag: ee8d60066517b067354d9bc27339693ddd985656
- name: app-v
  newName: manscalh/app-reports
  newTag: 6c9b906425b4b6842b20b81e8c8e1e3b08ac2a7a
