apiVersion: v1
kind: Service
metadata:
  name: app-reports-service
spec:
  type: LoadBalancer
  selector:
    app: app-reports
  ports:
  - port: 3003        #SERVICE URL
    targetPort: 3003  #CONTAINER
    # nodePort: 30001   #CLUSTER